// ABMNZN SDK 2016-08-23-p4cl0m9v
if (window.amazon == null || window.amazon.Login == null) {
(function() {
'use strict';var f=void 0,g=!0,h=null,i=!1;function j(a){return function(){return this[a]}}var k,n,q,r,s,aa;function ba(a,b){if(a===h||a===f)a={};for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d!==h&&d!==f)for(var e in d)a[e]=d[e]}return a}function u(a,b){var c=v.apply(f,arguments);ca("error",c);throw Error(c);}
function v(a,b){var c=arguments,d=1;return a.replace(/%((%)|[sid])/g,function(a){if(a[2])return a[2];a=c[d++];"object"==typeof a&&(window.JSON&&window.JSON.stringify)&&(a=window.JSON.stringify(a));return a})}function ca(a,b){window.console&&window.console.log&&("function"==typeof b&&(b=b()),b=v("[Amazon.%s] %s",a,b),window.console.log(b))}function w(a,b,c){b==h&&u("missing %s",a);typeof b!=c&&u("expected %s to be a %s",a,c)}
function da(a){var b=document.getElementById(a);b||(b=document.createElement("div"),b.setAttribute("id",a),b.setAttribute("width",0),b.setAttribute("height",0),b.setAttribute("style","position: absolute; left: -1000px; top: -1000px"),b.style.setAttribute&&b.style.setAttribute("cssText","position: absolute; left: -1000px; top: -1000px"),a=document.getElementById("amazon-root"),a||(a=document.createElement("div"),a.setAttribute("id","amazon-root"),document.body.appendChild(a)),a.appendChild(b));return b}
function ea(){this.a=[]}ea.prototype.b=function(a){var b=this.a;this.a=[];for(var c=0;c<b.length;c++)b[c].A&&this.a.push(b[c]);for(c=0;c<b.length;c++)b[c].t.apply(f,arguments)};var x,y,z,fa={'"':'"',"\\":"\\","/":"/",R:"\b",S:"\f",T:"\n",U:"\r",V:"\t"},ga;function A(a){throw{name:"SyntaxError",message:a,Q:y,text:ga};}function C(a){a&&a!==z&&A("Expected '"+a+"' instead of '"+z+"'");z=ga.charAt(y);y+=1;return z}
function ha(){var a;a="";"-"===z&&(a="-",C("-"));for(;"0"<=z&&"9">=z;)a+=z,C();if("."===z)for(a+=".";C()&&"0"<=z&&"9">=z;)a+=z;if("e"===z||"E"===z){a+=z;C();if("-"===z||"+"===z)a+=z,C();for(;"0"<=z&&"9">=z;)a+=z,C()}a=+a;if(isFinite(a))return a;A("Bad number")}
function ia(){var a,b,c="",d;if('"'===z)for(;C();){if('"'===z)return C(),c;if("\\"===z)if(C(),"u"===z){for(b=d=0;4>b;b+=1){a=parseInt(C(),16);if(!isFinite(a))break;d=16*d+a}c+=String.fromCharCode(d)}else if("string"===typeof fa[z])c+=fa[z];else break;else c+=z}A("Bad string")}function D(){for(;z&&" ">=z;)C()}
function ja(){switch(z){case "t":return C("t"),C("r"),C("u"),C("e"),g;case "f":return C("f"),C("a"),C("l"),C("s"),C("e"),i;case "n":return C("n"),C("u"),C("l"),C("l"),h}A("Unexpected '"+z+"'")}var E;
E=function(){D();switch(z){case "{":var a;a:{var b={};if("{"===z){C("{");D();if("}"===z){C("}");a=b;break a}for(;z;){a=ia();D();C(":");Object.hasOwnProperty.call(b,a)&&A('Duplicate key "'+a+'"');b[a]=E();D();if("}"===z){C("}");a=b;break a}C(",");D()}}A("Bad object");a=f}return a;case "[":a:{a=[];if("["===z){C("[");D();if("]"===z){C("]");break a}for(;z;){a.push(E());D();if("]"===z){C("]");break a}C(",");D()}}A("Bad array");a=f}return a;case '"':return ia();case "-":return ha();default:return"0"<=z&&
"9">=z?ha():ja()}};x=function(a,b){var c;ga=a;y=0;z=" ";c=E();D();z&&A("Syntax error");return"function"===typeof b?function e(a,c){var p,m,B=a[c];if(B&&"object"===typeof B)for(p in B)Object.prototype.hasOwnProperty.call(B,p)&&(m=e(B,p),m!==f?B[p]=m:delete B[p]);return b.call(a,c,B)}({"":c},""):c};var F;function G(a){return 10>a?"0"+a:a}
function ka(a){la.lastIndex=0;return la.test(a)?'"'+a.replace(la,function(a){var c=ma[a];return"string"===typeof c?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}
function H(a,b){var c,d,e,l,t=I,p,m=b[a];m&&("object"===typeof m&&"function"===typeof m.toJSON)&&(m=m.toJSON(a));"function"===typeof J&&(m=J.call(b,a,m));switch(typeof m){case "string":return ka(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);case "object":if(!m)return"null";I+=K;p=[];if("[object Array]"===Object.prototype.toString.apply(m)){l=m.length;for(c=0;c<l;c+=1)p[c]=H(c,m)||"null";e=0===p.length?"[]":I?"[\n"+I+p.join(",\n"+I)+"\n"+t+"]":"["+
p.join(",")+"]";I=t;return e}if(J&&"object"===typeof J){l=J.length;for(c=0;c<l;c+=1)"string"===typeof J[c]&&(d=J[c],(e=H(d,m))&&p.push(ka(d)+(I?": ":":")+e))}else for(d in m)Object.prototype.hasOwnProperty.call(m,d)&&(e=H(d,m))&&p.push(ka(d)+(I?": ":":")+e);e=0===p.length?"{}":I?"{\n"+I+p.join(",\n"+I)+"\n"+t+"}":"{"+p.join(",")+"}";I=t;return e}}
"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+G(this.getUTCMonth()+1)+"-"+G(this.getUTCDate())+"T"+G(this.getUTCHours())+":"+G(this.getUTCMinutes())+":"+G(this.getUTCSeconds())+"Z":h},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});
var la=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,I,K,ma={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},J;F=function(a,b,c){var d;K=I="";if("number"===typeof c)for(d=0;d<c;d+=1)K+=" ";else"string"===typeof c&&(K=c);if((J=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return H("",{"":a})};
function L(a){var b="",c;for(c in a)b&&(b+="&"),b+=encodeURIComponent(c)+"="+encodeURIComponent(a[c]+"");return b}function na(a,b){for(var c=0;c<b.length;c++){var d=b[c];""!=d&&!a.b.hasOwnProperty(d)&&(a.a.push(d),a.b[d]=1)}}n=function(a){this.a=[];a="string"==typeof a?a.split(/\s+/):a;this.b={};na(this,a)};n.prototype.contains=function(a){for(var b=0;b<a.a.length;b++)if(!this.b.hasOwnProperty(a.a[b]))return i;return g};n.prototype.add=function(a){na(this,a.a)};
n.prototype.c=function(a){for(var b=0;b<this.a.length;b++)a(this.a[b])};n.prototype.toString=function(){return this.a.join(" ")};q={};var oa=h;q.w=function(){return oa};q.h=function(a){w("domain",a,"string");var a=a.replace(/^\s+|\s+$/g,""),b="."+window.location.hostname;"."!=a.charAt(0)&&(a="."+a);b.indexOf(a)!=b.length-a.length&&u("Site domain must contain the current page's domain");oa=a};q.n=function(){};q.n.prototype.getItem=function(){};q.n.setItem=function(){};q.n.removeItem=function(){};
function M(){}M.prototype.getItem=function(a){a=RegExp("(?:^|;)\\s*"+escape(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*)(?:;|$)").exec(document.cookie);return a==h?h:unescape(a[1])};M.prototype.setItem=function(a,b,c){var d;d=c==h?"Fri, 31 Dec 9999 23:59:59 GMT":(new Date((new Date).getTime()+1E3*c)).toGMTString();var e=q.w(),e=e==h?"":";Domain="+e,l=pa(N(window.location.href+""))?"":";Secure";document.cookie=a+"="+escape(b)+("session"==c?"":";Expires="+d)+e+";Path=/"+l};
M.prototype.removeItem=function(a){q.d.setItem(a,"null",0)};q.d=new M;function O(a){this.a=a}O.prototype.getItem=function(a){return this.a.getItem(a)};O.prototype.setItem=function(a,b,c){this.a.setItem(a,b,c)};O.prototype.removeItem=function(a){q.d.removeItem(a)};q.l=new O(q.d);
r={G:function(a,b){if("bearer"==a.token_type){var c=F({access_token:a.access_token,max_age:b,expiration_date:(new Date).getTime()+1E3*b,client_id:s.v(),scope:a.scope});q.l.setItem("amazon_Login_state_cache",c,"session")}},u:function(){var a=q.l.getItem("amazon_Login_state_cache");return a!=h&&(a=x(a),a!=h&&a.expiration_date>(new Date).getTime())?(a.scope=new n(a.scope),a):h},o:function(){q.l.removeItem("amazon_Login_state_cache")}};
function qa(){return window.XMLHttpRequest&&"withCredentials"in new window.XMLHttpRequest||"undefined"!==typeof window.XDomainRequest?g:i}function P(a,b,c,d,e,l){this.a=new Q(a,b,c);("string"!=typeof d||!d)&&u("missing or invalid path: %s",d);this.f=d;"object"==typeof e&&(e=L(e));e&&"string"!=typeof e&&u("invalid query: %s",e);this.c=e||"";"object"==typeof l&&(l=L(l));l&&"string"!=typeof l&&u("invalid fragment: %s",l);this.b=l||""}
function N(a){var b=document.createElement("div");b.innerHTML="<a></a>";b.firstChild.href=a;b.innerHTML=b.innerHTML;a=b.firstChild;""==a.host&&(a.href=a.href);b=a.port;if(!b||"0"==b)b=h;var c=a.pathname;c?"/"!=c[0]&&(c="/"+c):c="/";return new P(a.protocol,a.hostname,b,c,a.search.substring(1),a.href.split("#")[1]||"")}k=P.prototype;k.scheme=function(){return this.a.scheme()};k.host=function(){return this.a.host()};k.port=function(){return this.a.port()};k.path=j("f");k.g=j("c");k.i=j("b");
function pa(a){var b="http"==a.a.scheme(),a=a.a.host();return b&&("localhost"==a||"127.0.0.1"==a)}k.toString=function(){var a=this.a.toString(),a=a+this.f,a=a+(this.c?"?"+this.c:"");return a+=this.b?"#"+this.b:""};function ra(a,b){return new P(b.scheme!==f?b.scheme:a.scheme(),b.host!==f?b.host:a.host(),b.port!==f?b.port:a.port(),b.path!==f?b.path:a.path(),b.g!==f?b.g:a.g(),b.i!==f?b.i:a.i())}
function Q(a,b,c){var d;("string"!=typeof a||!(d=a.match(/^(https?)(:(\/\/)?)?$/i)))&&u("missing or invalid scheme: %s",a);this.a="http"==d[1]?"http":"https";if(!(a="string"!=typeof b))if(!(a=!b))("string"!=typeof b||!b)&&u("missing or invalid input: %s",b),a=0==b.replace(/^\s+|\s+$/g,"").length;a&&u("missing or invalid host: %s",b);this.c=b;if(c&&((c+"").match(/^\d+$/)||u("invalid port: %s",c),80==c&&"http"==this.a||443==c&&"https"==this.a))c=h;this.b=c?c+"":h}var sa=/^(http|https):\/\/(.+?)(:(\d+))?$/i;
Q.prototype.scheme=j("a");Q.prototype.host=j("c");Q.prototype.port=j("b");Q.prototype.toString=function(){var a;a=""+(this.a+"://");a+=this.c;return a+=this.b?":"+this.b:""};function R(a,b,c,d){return new P(a.a,a.c,a.b,b,c,d)}function ta(a){for(var b="",c=0;c<a;c++)b+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return b}var S={},T=h;
function ua(a){var b=U;a:if(window.__toucanForceProxyOriginTo){var b=window.__toucanForceProxyOriginTo,c=b.match(sa);if(c)b=new Q(c[1],c[2],c[4]?c[4]-0:h);else throw u("invalid origin: %s",b),Error();}else if(window.__toucanForceProxyOriginToThisOrigin)b=N(window.location.href+"").a;else{if(c=b.host().match(/^([\w\-\.]+\.)?amazon\.([\w\.]+)$/)){if("https"==b.scheme()){b=new Q("https","api-cdn.amazon."+c[2],h);break a}u("no proxy origin; unsupported non-https target origin for amazon: %s",b)}u("no proxy origin; unsupported target origin: %s",
b);throw Error();}c=b;if(!T){var d=window.postMessage?"pm":"fr";window.__toucanForceTransport&&(d=window.__toucanForceTransport);if("pm"==d)d=new V;else if("fr"==d)d=new W;else throw u("unknown transport: %s",d),Error();T=d;T.b(c,function(a,b){var c=S[a];c&&c.b(b)})}var d=b,e=T,c=d.host().replace(/[^a-z0-9]/ig,"_");d.port()&&(c+="_"+d.port());var c=v("amazon-proxy-%s-%s",d.scheme(),c),l=document.getElementById(c);l||(l=document.createElement("iframe"),l.setAttribute("id",c),l.setAttribute("name",
c),l.setAttribute("src",va(d,e).toString()),da("amazon-proxy-root").appendChild(l));d=ta(16);S[d]||(S[d]=new ea);S[d].a.push({t:a,A:i});a=b;b={uri:wa().toString(),proxy:c,topic:d,version:"1"};return R(a,"/sdk/2016-08-23-p4cl0m9v/topic.html",b,"")}function wa(){return ra(N(window.location.href+""),{g:"",i:""})}function va(a,b){var c={uri:wa().toString(),tr:b.name()};return R(a,"/sdk/2016-08-23-p4cl0m9v/proxy.html",{version:"1"},c)}var xa=/^ABMNZNXDC;([\w\d\_\-]+);(.*)$/;
function ya(a){var b=a.match(xa);if(b){a={};a.id=b[1];for(var c={},b=b[2].split("&"),d=0;d<b.length;d++){var e=b[d].split("=");2==e.length&&(c[e[0]]=decodeURIComponent(e[1].replace(/\+/g," ")))}a.data=c;return a}return h}function V(){this.a=f}V.prototype.name=function(){return"pm"};
V.prototype.b=function(a,b){if(this.a===f){var c=this.a=new ea,d=function(a){var b;(b=ya(a.data))&&c.b(a.origin,b.id,b.data)};window.addEventListener?window.addEventListener("message",d,i):window.attachEvent?window.attachEvent("onmessage",d):u("cannot attach message event")}var e=a.toString();this.a.a.push({t:function(a,c,d){a!=e||b(c,d)},A:g})};V.prototype.send=function(a,b,c){var d=a.a;setTimeout(function(){window.parent.postMessage(v("%s;%s;%s","ABMNZNXDC",b,L(c)),d.toString())},1)};
function W(){}W.prototype.name=function(){return"fr"};W.prototype.b=function(a,b){window.__toucanInvokeFragment=function(a,d){b(a,d)}};W.prototype.send=function(a,b,c){var d=a.g();(d=d||"")&&(d+="&");d=d+"ABMNZNXDC"+("="+ta(8));a=ra(a,{g:d,i:v("%s;%s;%s","ABMNZNXDC",b,L(c))});b=document.createElement("iframe");b.setAttribute("src",a.toString());document.body.appendChild(b)};var za=window.location.href.split("#")[1]||"";
if(za){var Aa=ya(za);Aa&&(document.documentElement.style.display="none","function"==typeof window.parent.parent.__toucanInvokeFragment&&window.parent.parent.__toucanInvokeFragment(Aa.id,Aa.data))}function Ba(a){var b=a.match(Ca);b||u("invalid domain: %s",a);var c=b[2]?b[2].toLowerCase():"https";"https"!=c&&u("invalid domain: %s; scheme must be https",a);a=b[3];a.match(/^amazon\.[a-z\.]+$/)&&(a="www."+a);return new Q(c,a,b[5])}function Da(){X!=h&&("function"==typeof X.close&&X.close(),X=h)}
function Ea(a,b,c){b={client_id:Y,redirect_uri:b,response_type:a.response_type,scope:a.scope.toString(),language:Fa,ui_locales:Ga};a.response_mode&&(b.response_mode=a.response_mode);a.direct_post_uri&&(b.direct_post_uri=a.direct_post_uri);a.scope_data&&(b.scope_data=a.scope_data);Ha&&(b.sandbox=g);a.state&&(b.state=a.state);c&&(b.exac=c);return R(U,"/ap/oa",b)}
function Ia(a,b,c){Z=i;b.access_token!=h?(c=parseInt(b.expires_in,10),c=60>=c?c:c-Math.min(Math.floor(0.1*c),300),r.G(b,c),s.C()?q.d.setItem(s.e,b.access_token,c):q.d.removeItem(s.e)):c&&q.d.removeItem(s.e);a.z(b);a=Ja;Ja=[];for(b=0;b<a.length;b++)Ka(a[b])}
function La(a,b){var b=b+(-1==b.indexOf("?")?"?":"&"),b=b+L(a),c=N(b),d=N(window.location.href+"");"https"!=c.scheme()&&!pa(c)&&u("attempted redirect to %s but scheme is not HTTPS",b);c.host()!=d.host()&&u("attempted redirect to %s but it does not match current host %s",c.host(),d.host());c=b;Da();window.location.href=c}
function Ma(a){var b=this;this.b=a;this.p=h;this.f=[];this.c=h;this.a={status:h,onComplete:function(a){"string"!=typeof a&&"function"!=typeof a&&u("onComplete expects handler parameter to be a function or a string");var d=b.a.status==Na.r;"string"==typeof a?d?La(b.c,a):b.p=a:"function"==typeof a&&(d?setTimeout(function(){a(b.a)},0):b.f.push(a));return b.a}}}
function Ka(a){var b=a.b,c=h;if(b.interactive==$.ALWAYS)r.o();else{var d=h;s.C()&&(d=q.d.getItem(s.e));if(c=r.u())"token"==b.response_type&&b.scope.add(c.scope),d?d!=c.access_token&&(r.o(),c=h):d=c.access_token;var e;if(c&&c.scope.contains(b.scope)&&"token"==b.response_type)e={access_token:c.access_token,token_type:"bearer",expires_in:Math.floor((c.expiration_date-(new Date).getTime())/1E3),scope:c.scope.toString()},b.state!=h&&(e.state=b.state);else if(b.interactive==$.NEVER){if(Z){Ja.push(a);a.q(Na.F);
return}if(d){b=d;Z=g;var l=da("amazon-client-credentials-root"),c=da("amazon-client-credentials-root"),t=ta(16),d=document.createElement("iframe");d.setAttribute("name",t);c.appendChild(d);0==document.getElementsByName(t).length&&(c.removeChild(d),d=document.createElement('<iframe name="'+t+'"/>'),c.appendChild(d));d.setAttribute("id",t);var p=document.createElement("form");l.appendChild(p);p.setAttribute("method","POST");p.setAttribute("target",t);d=ua(function(b){l.removeChild(p);var c=document.getElementById(t);
c!=h&&c.parentNode!=h&&c.parentNode.removeChild(c);b==h&&(b={error:"server_error",description:"Server error."});Ia(a,b,i)});c=a.b;b={client_id:Y,exac:b,grant_type:"client_credentials",redirect_uri:d,response_type:c.response_type,scope:c.scope};c.state!=h&&(b.state=c.state);c.response_mode!=h&&(b.response_mode=c.response_mode);c.direct_post_uri!=h&&(b.direct_post_uri=c.direct_post_uri);c.scope_data!=h&&(b.scope_data=c.scope_data);c.optional_scope!=h&&(b.claims=c.optional_scope);p.setAttribute("action",
R(U,"/ap/oa",b).toString());p.submit();return}e={error:"invalid_grant",error_description:"invalid grant"}}if(e){setTimeout(function(){a.z(e)},0);return}}b=d;Z=g;c=ua(function(b){Da();Ia(a,b,g)});b=Ea(a.b,c,b);c=(window.screenX!==f?window.screenX:window.screenLeft)+Math.floor(((window.outerWidth!==f?window.outerWidth:document.documentElement.clientWidth)-800)/2);d=(window.screenY!==f?window.screenY:window.screenTop)+Math.floor(((window.outerHeight!==f?window.outerHeight:document.documentElement.clientHeight)-
540)/2);c=v("left=%s,top=%s,width=%s,height=%s,location=1,scrollbars=1",0>c?0:c,0>d?0:d,800,540);X=window.open(b.toString(),"amazonloginpopup",c)}s={m:{NorthAmerica:"NA",Europe:"EU",AsiaPacific:"APAC"},e:"amazon_Login_accessToken"};var Ca=/^((http|https):\/\/)?([a-z0-9\-\.]+)(:(\d+))?\/?$/i,$={ALWAYS:"always",j:"auto",NEVER:"never"},X=h,Z=i,Ja=[],Na={F:"queued",D:"in_progress",r:"complete"},Y=f;s.v=function(){return Y};s.K=function(a){a.match(/^[\w\-\.]+$/)||u("invalid client ID: %s",a);Y=a};
var Oa="www.amazon.com",U=new Q("https",Oa,h),Pa=new Q("https","api.amazon.com",h);s.w=function(){return Oa};s.H=function(){return Pa};var Ha=i;s.O=function(a){"number"==typeof a&&(a=!!a);w("sandboxMode",a,"boolean");Ha=a};s.h=function(a){U=Ba(a);Oa=a};s.k=function(a){Pa=Ba(a)};
s.N=function(a){a&&(a===s.m.Europe?(s.h("https://eu.account.amazon.com"),s.k("https://api.amazon.co.uk")):a===s.m.AsiaPacific?(s.h("https://apac.account.amazon.com"),s.k("https://api.amazon.co.jp")):(s.h("https://www.amazon.com"),s.k("https://api.amazon.com")))};var Fa="";s.L=function(a){Fa=a};var Ga="";s.M=function(a){Ga=a};s.I=function(){return U};var Qa=i;s.C=function(){return Qa};
s.P=function(a){a==h?u("missing useCookie"):"number"==typeof a?a=!!a:"boolean"!=typeof a&&u("expected useCookie to be a boolean");Qa=a};Ma.prototype.z=function(a){this.c=a;ba(this.a,a);this.q(Na.r);for(a=0;a<this.f.length;a++)this.f[a](this.a);this.p!=h&&La(this.c,this.p)};Ma.prototype.q=function(a){this.a.status=a};
s.s=function(a,b){2>arguments.length&&u("authorize expects two arguments (options, next)");a&&"object"!=typeof a&&u("authorize expects options parameter to be an object");b!=h&&("function"!=typeof b&&"string"!=typeof b)&&u("authorize expects next parameter to be a function or a string");var c=ba({interactive:$.j,popup:g,response_type:"token",response_mode:f,direct_post_uri:f,state:f,scope:f,scope_data:f,optional_scope:f},a||{});w("options.response_type",c.response_type,"string");c.scope||u("missing options.scope");
c.scope.constructor!==Array&&"string"!=typeof c.scope&&u("expected options.scope to be a string or array");c.scope=new n(c.scope);c.response_mode&&w("options.response_mode",c.response_mode,"string");c.direct_post_uri&&w("options.direct_post_uri",c.direct_post_uri,"string");c.scope_data&&(c.scope_data=F(c.scope_data));c.interactive==h?c.interactive=$.j:c.interactive!=$.j&&(c.interactive!=$.ALWAYS&&c.interactive!=$.NEVER)&&u("expected options.interactive to be one of '"+$.j+"', '"+$.ALWAYS+"', or '"+
$.NEVER+"'");if(c.optional_scope){c.optional_scope.constructor!==Array&&"string"!=typeof c.optional_scope&&u("expected options.optional_scope to be a string or array");c.interactive!=$.NEVER&&u("options.optional_scope is only supported for options.interactive = never");var d=new n(c.optional_scope);c.scope.add(d);var e={id_token:{}};d.c(function(a){e.id_token[a]={essential:i}});c.optional_scope=F(e)}a=c;d=new Ma(a);c=d.a;d.q(Na.D);if(b!=h)c.onComplete(b);a.popup?Ka(d):("string"!=typeof b&&u("next must be redirect URI if !options.popup"),
d=Ea(a,N(b+""),h).toString(),window.top.location.href=d);return c};function Ra(a,b){var c;try{c=x(a)}catch(d){c=h}if(c&&c.Error){var e={success:i};e.error=v("%s: %s",c.Error.Code||"UnknownError",c.Error.Message||"An unknown error occurred");b(e)}else c&&c.Profile?(e={success:g},e.profile=c.Profile,b(e)):(e={success:i,error:"UnknownError: Incomprehensible response from profile endpoint"},b(e))}
aa={B:function(a,b){if(b==h&&"function"==typeof a)b=a,s.s({scope:"profile"},function(a){a.error==h?aa.B(a.access_token,b):b({success:i,error:a.error})});else if(w("accessToken",a,"string"),w("callback",b,"function"),qa()){var c=R(s.I(),"/ap/user/profile",{access_token:a},""),d;if(window.XDomainRequest)d=new window.XDomainRequest,d.onload=function(){Ra(d.responseText,b)};else{var e=i;d=new window.XMLHttpRequest;d.onreadystatechange=function(){e||4!=d.readyState||(e=g,Ra(d.responseText,b))}}d.open("GET",
c,g);d.send()}else b({success:i,error:"UnsupportedOperation: Cannot retrieve profile in this browser"})}};function Sa(a){var b,c;try{c=x(a).response}catch(d){c=f}if(!c||c.error)a="UnknownError",b="An unknown error ocurred",c&&(c.error&&c.error.code&&c.error.message)&&(a=c.error.code,b=c.error.message),b=v("%s: %s",a,b);b&&ca("logout",b)}
s.J=function(){var a=q.d.getItem(s.e),b=r.u();a&&q.d.removeItem(s.e);!a&&b&&(a=b.access_token);r.o();if(a){qa()||ca("logout","UnsupportedOperation: Cannot remotely logout in this browser");var b=R(s.H(),"/auth/relyingPartyLogout",h,h).toString(),c={};c.token=a;c.token_type="bearer";var d;if(window.XDomainRequest)d=new window.XDomainRequest,d.onload=function(){Sa(d.responseText)};else{var e=i;d=new window.XMLHttpRequest;d.onreadystatechange=function(){e||4!=d.readyState||(e=g,Sa(d.responseText))}}d.open("POST",
b,g);d.send(F(c))}};window.amazon=window.amazon||{};window.amazon.Login=window.amazon.Login||{};window.amazon.Login.getClientId=function(){return s.v()};window.amazon.Login.setClientId=function(a){return s.K(a)};window.amazon.Login.setDomain=function(a){return s.h(a)};window.amazon.Login.setAPIDomain=function(a){return s.k(a)};window.amazon.Login.setSandboxMode=function(a){return s.O(a)};window.amazon.Login.setSiteDomain=function(a){return q.h(a)};window.amazon.Login.Region=s.m;
window.amazon.Login.setRegion=function(a){return s.N(a)};window.amazon.Login.setLanguage=function(a){return s.L(a)};window.amazon.Login.setLanguageHint=function(a){return s.M(a)};window.amazon.Login.setUseCookie=function(a){return s.P(a)};window.amazon.Login.authorize=function(a,b){return s.s(a,b)};window.amazon.Login.logout=function(){return s.J()};window.amazon.Login.retrieveProfile=function(a,b){return aa.B(a,b)};if("function"==typeof window.onAmazonLoginReady)window.onAmazonLoginReady();

})();
}
